In [1]:
import os
import pandas as pd

# First, let's see everything in /kaggle/input/
print("Full contents of /kaggle/input/:")
for root, dirs, files in os.walk('/kaggle/input/'):
    level = root.replace('/kaggle/input/', '').count(os.sep)
    indent = ' ' * 2 * level
    print(f'{indent}{os.path.basename(root)}/')
    subindent = ' ' * 2 * (level + 1)
    for file in files[:10]:  # Show first 10 files in each directory
        print(f'{subindent}{file}')
    if len(files) > 10:
        print(f'{subindent}... and {len(files)-10} more files')

# Now search specifically for CSV files anywhere
print("\n\nSearching for CSV files:")
csv_files = []
for root, dirs, files in os.walk('/kaggle/input/'):
    for file in files:
        if file.endswith('.csv'):
            csv_files.append(os.path.join(root, file))

if csv_files:
    print(f"Found {len(csv_files)} CSV files:")
    for csv_file in csv_files:
        print(f"  - {csv_file}")
        # Try to read the first few rows of each CSV
        try:
            df_sample = pd.read_csv(csv_file, nrows=2)
            print(f"    Columns: {df_sample.columns.tolist()}")
            print(f"    Shape: {df_sample.shape}")
        except Exception as e:
            print(f"    Error reading: {e}")
else:
    print("No CSV files found in /kaggle/input/")
    
    # Check if there might be compressed files
    print("\nChecking for compressed files:")
    for root, dirs, files in os.walk('/kaggle/input/'):
        for file in files:
            if file.endswith(('.zip', '.tar', '.gz', '.7z')):
                print(f"  - {os.path.join(root, file)}")

Full contents of /kaggle/input/:
/
datasets/
  badcodebuilder/
    insdn-dataset/
      InSDN_DatasetCSV/
        metasploitable-2.csv
        Normal_data.csv
        OVS.csv
notebooks/
  badcodebuilder/
    ddos-sdn-insdn/
      __results__.html
      __resultx__.html
      __notebook__.ipynb
      __output__.json
      custom.css


Searching for CSV files:
Found 3 CSV files:
  - /kaggle/input/datasets/badcodebuilder/insdn-dataset/InSDN_DatasetCSV/metasploitable-2.csv
    Columns: ['Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd 

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("badcodebuilder/insdn-dataset")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/datasets/badcodebuilder/insdn-dataset


In [3]:
import pandas as pd
import os

# The path from kagglehub
path = "/root/.cache/kagglehub/datasets/badcodebuilder/insdn-dataset/versions/1"  # or whatever path was printed

# If you didn't save the path variable, run this:
import kagglehub
path = kagglehub.dataset_download("badcodebuilder/insdn-dataset")
print(f"Dataset path: {path}")

# List all files in the dataset
print(f"\nFiles in dataset:")
files = os.listdir(path)
for file in files:
    print(f"  - {file}")
    file_path = os.path.join(path, file)
    if os.path.isfile(file_path) and file.endswith('.csv'):
        # Check file size
        size = os.path.getsize(file_path) / (1024 * 1024)  # MB
        print(f"    Size: {size:.2f} MB")

# Load the CSV files
csv_files = [f for f in files if f.endswith('.csv')]
df_dict = {}

for file in csv_files:
    file_path = os.path.join(path, file)
    df = pd.read_csv(file_path)
    df_dict[file] = df
    print(f"\n{file}:")
    print(f"  - Rows: {len(df)}")
    print(f"  - Columns: {len(df.columns)}")
    print(f"  - Column names (first 10): {df.columns[:10].tolist()}")
    print(f"  - Data types:")
    print(f"    {df.dtypes.value_counts()}")
    print(f"  - First 2 rows:")
    print(df.head(2))
    print(f"  - Sample values from first row: {df.iloc[0].tolist()[:5]}")

# Combine all dataframes
if df_dict:
    all_dfs = []
    for name, df in df_dict.items():
        df_copy = df.copy()
        df_copy['source'] = name.replace('.csv', '')
        all_dfs.append(df_copy)
    
    combined_df = pd.concat(all_dfs, ignore_index=True)
    print(f"\n{'='*50}")
    print(f"Combined dataset:")
    print(f"  - Total rows: {len(combined_df)}")
    print(f"  - Total columns: {len(combined_df.columns)}")
    
    # Check for label/target column
    label_cols = [col for col in combined_df.columns if 'label' in col.lower() or 'class' in col.lower()]
    if label_cols:
        print(f"\n  - Potential label columns: {label_cols}")
        for col in label_cols:
            print(f"    {col} distribution:")
            print(f"    {combined_df[col].value_counts()}")
    
    # Save for later use
    df = combined_df
    print(f"\n✅ Dataset loaded and ready for training!")
    print(f"📊 Shape: {df.shape}")
    print(f"📋 Columns: {df.columns.tolist()}")

Dataset path: /kaggle/input/datasets/badcodebuilder/insdn-dataset

Files in dataset:
  - InSDN_DatasetCSV


In [4]:
import os
for root, dirs, files in os.walk('/kaggle/input'):
    for f in files:
        if f.endswith('.csv'):
            print(os.path.join(root, f))

/kaggle/input/datasets/badcodebuilder/insdn-dataset/InSDN_DatasetCSV/metasploitable-2.csv
/kaggle/input/datasets/badcodebuilder/insdn-dataset/InSDN_DatasetCSV/Normal_data.csv
/kaggle/input/datasets/badcodebuilder/insdn-dataset/InSDN_DatasetCSV/OVS.csv


In [5]:
import pandas as pd

p_normal = "/kaggle/input/datasets/badcodebuilder/insdn-dataset/InSDN_DatasetCSV/Normal_data.csv"
p_meta   = "/kaggle/input/datasets/badcodebuilder/insdn-dataset/InSDN_DatasetCSV/metasploitable-2.csv"
p_ovs    = "/kaggle/input/datasets/badcodebuilder/insdn-dataset/InSDN_DatasetCSV/OVS.csv"

for name, p in [("Normal", p_normal), ("Metasploitable", p_meta), ("OVS", p_ovs)]:
    df = pd.read_csv(p, nrows=3)
    print(f"\n=== {name} ({df.shape[1]} cols) ===")
    print(list(df.columns))


=== Normal (84 cols) ===
['Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size 

In [6]:
df_normal = pd.read_csv(p_normal, low_memory=False)
df_meta   = pd.read_csv(p_meta, low_memory=False)
df_ovs    = pd.read_csv(p_ovs, low_memory=False)

for d in (df_normal, df_meta, df_ovs):
    d.columns = [c.strip() for c in d.columns]

df_all = pd.concat([df_normal, df_meta, df_ovs], ignore_index=True)
print(df_all.shape)
print(df_all['Label'].value_counts())

(343889, 84)
Label
Probe         98129
DDoS          73529
Normal        68424
DoS           53616
DDoS          48413
BFA            1405
Web-Attack      192
BOTNET          164
U2R              17
Name: count, dtype: int64


In [7]:
def map_label_to_class(raw_label):
    raw = str(raw_label).strip().lower()
    if raw in ("normal", "benign"):
        return "Normal"
    if "ddos" in raw:
        return "DDoS"
    if "dos" in raw and "ddos" not in raw:
        return "DoS"
    if "probe" in raw or "scan" in raw:
        return "Probe"
    if "bfa" in raw or "brute" in raw:
        return "BFA"
    if "web" in raw:
        return "Web-Attack"
    if "bot" in raw:
        return "Botnet"
    if "u2r" in raw or "exploit" in raw:
        return "U2R"
    return "Unknown"

df_all['class'] = df_all['Label'].apply(map_label_to_class)
print(df_all['class'].value_counts())
print("Unknown labels found:", df_all[df_all['class'] == 'Unknown']['Label'].unique())

class
DDoS          121942
Probe          98129
Normal         68424
DoS            53616
BFA             1405
Web-Attack       192
Botnet           164
U2R               17
Name: count, dtype: int64
Unknown labels found: []


In [8]:
#feature engineering

import numpy as np

work = df_all.copy()
work['duration_sec'] = (work['Flow Duration'] / 1_000_000.0).clip(lower=0.001)
work['packet_count'] = work['Tot Fwd Pkts'] + work['Tot Bwd Pkts']
work['byte_count']   = work['TotLen Fwd Pkts'] + work['TotLen Bwd Pkts']
work['protocol']     = work['Protocol']
work['avg_packet_size'] = work['byte_count'] / work['packet_count'].replace(0, np.nan)
work['packet_rate']     = work['packet_count'] / work['duration_sec']
work['byte_rate']       = work['byte_count'] / work['duration_sec']

feature_cols = ['duration_sec', 'packet_count', 'byte_count',
                 'avg_packet_size', 'packet_rate', 'byte_rate', 'protocol']

work = work.replace([np.inf, -np.inf], np.nan)
before = len(work)
work = work.dropna(subset=feature_cols + ['class'])
work = work[work['class'] != 'Unknown']
print(f"Dropped {before - len(work)} rows. Remaining: {len(work)}")

X = work[feature_cols]
y = work['class']
print(y.value_counts())

Dropped 0 rows. Remaining: 343889
class
DDoS          121942
Probe          98129
Normal         68424
DoS            53616
BFA             1405
Web-Attack       192
Botnet           164
U2R               17
Name: count, dtype: int64


In [9]:
!pip install -q imbalanced-learn

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE
import joblib

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

# k_neighbors capped low because U2R has very few samples in the training split
sm = SMOTE(random_state=42, k_neighbors=3)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)
print("After SMOTE:", y_train_res.value_counts())

clf = RandomForestClassifier(
    n_estimators=200, class_weight="balanced", random_state=42, n_jobs=-1
)
clf.fit(X_train_res, y_train_res)

After SMOTE: class
Probe         91456
Normal        91456
DDoS          91456
DoS           91456
BFA           91456
Web-Attack    91456
Botnet        91456
U2R           91456
Name: count, dtype: int64


RandomForestClassifier(class_weight='balanced', n_estimators=200, n_jobs=-1,
                       random_state=42)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix, f1_score

y_pred = clf.predict(X_test)

print("=== Classification Report ===")
print(classification_report(y_test, y_pred, zero_division=0))

macro_f1 = f1_score(y_test, y_pred, average='macro')
weighted_f1 = f1_score(y_test, y_pred, average='weighted')
print(f"\nMacro-F1 (treats all classes equally): {macro_f1:.4f}")
print(f"Weighted-F1 (accounts for class size):  {weighted_f1:.4f}")

print("\n=== Confusion Matrix ===")
labels_sorted = sorted(y.unique())
print("Classes:", labels_sorted)
print(confusion_matrix(y_test, y_pred, labels=labels_sorted))

=== Classification Report ===
              precision    recall  f1-score   support

         BFA       0.34      0.66      0.45       351
      Botnet       0.46      0.93      0.62        41
        DDoS       1.00      1.00      1.00     30486
         DoS       0.96      0.97      0.96     13404
      Normal       0.96      0.91      0.93     17106
       Probe       0.96      0.83      0.89     24533
         U2R       0.75      0.75      0.75         4
  Web-Attack       0.01      0.88      0.02        48

    accuracy                           0.93     85973
   macro avg       0.68      0.87      0.70     85973
weighted avg       0.97      0.93      0.95     85973


Macro-F1 (treats all classes equally): 0.7033
Weighted-F1 (accounts for class size):  0.9474

=== Confusion Matrix ===
Classes: ['BFA', 'Botnet', 'DDoS', 'DoS', 'Normal', 'Probe', 'U2R', 'Web-Attack']
[[  233     1     0    13    14    54     1    35]
 [    0    38     0     0     1     2     0     0]
 [    0     0 3

In [12]:
from imblearn.over_sampling import SMOTE

# Only meaningfully oversample classes with enough real diversity to interpolate safely.
# Leave Web-Attack and U2R alone - too few real points, SMOTE distorts more than it helps.
# class_weight='balanced' in the RF still gives them a boost during training.
sampling_strategy = {
    "BFA": 8000,      # up from ~1050 real training samples
    "Botnet": 3000,   # up from ~120
}

sm2 = SMOTE(random_state=42, k_neighbors=3, sampling_strategy=sampling_strategy)
X_train_res2, y_train_res2 = sm2.fit_resample(X_train, y_train)
print(y_train_res2.value_counts())

clf2 = RandomForestClassifier(
    n_estimators=200, class_weight="balanced", random_state=42, n_jobs=-1
)
clf2.fit(X_train_res2, y_train_res2)

y_pred2 = clf2.predict(X_test)
from sklearn.metrics import classification_report, f1_score
print(classification_report(y_test, y_pred2, zero_division=0))
print("Macro-F1:", f1_score(y_test, y_pred2, average='macro'))

class
DDoS          91456
Probe         73596
Normal        51318
DoS           40212
BFA            8000
Botnet         3000
Web-Attack      144
U2R              13
Name: count, dtype: int64
              precision    recall  f1-score   support

         BFA       0.54      0.67      0.60       351
      Botnet       0.55      0.88      0.68        41
        DDoS       1.00      1.00      1.00     30486
         DoS       0.96      0.97      0.97     13404
      Normal       0.96      0.91      0.94     17106
       Probe       0.96      0.84      0.90     24533
         U2R       1.00      0.75      0.86         4
  Web-Attack       0.01      0.90      0.02        48

    accuracy                           0.93     85973
   macro avg       0.75      0.86      0.74     85973
weighted avg       0.97      0.93      0.95     85973

Macro-F1: 0.7445641003890351


In [13]:
clf2 = RandomForestClassifier(
    n_estimators=200, class_weight="balanced", random_state=42, n_jobs=-1
)
clf2.fit(X_train_res2, y_train_res2)

y_pred2 = clf2.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, f1_score

print("=== Classification Report (selective SMOTE) ===")
print(classification_report(y_test, y_pred2, zero_division=0))

macro_f1_2 = f1_score(y_test, y_pred2, average='macro')
weighted_f1_2 = f1_score(y_test, y_pred2, average='weighted')
print(f"\nMacro-F1: {macro_f1_2:.4f}")
print(f"Weighted-F1: {weighted_f1_2:.4f}")

print("\n=== Confusion Matrix ===")
labels_sorted = sorted(y.unique())
print("Classes:", labels_sorted)
print(confusion_matrix(y_test, y_pred2, labels=labels_sorted))

=== Classification Report (selective SMOTE) ===
              precision    recall  f1-score   support

         BFA       0.54      0.67      0.60       351
      Botnet       0.55      0.88      0.68        41
        DDoS       1.00      1.00      1.00     30486
         DoS       0.96      0.97      0.97     13404
      Normal       0.96      0.91      0.94     17106
       Probe       0.96      0.84      0.90     24533
         U2R       1.00      0.75      0.86         4
  Web-Attack       0.01      0.90      0.02        48

    accuracy                           0.93     85973
   macro avg       0.75      0.86      0.74     85973
weighted avg       0.97      0.93      0.95     85973


Macro-F1: 0.7446
Weighted-F1: 0.9504

=== Confusion Matrix ===
Classes: ['BFA', 'Botnet', 'DDoS', 'DoS', 'Normal', 'Probe', 'U2R', 'Web-Attack']
[[  235     1     0     7    15    62     0    31]
 [    0    36     0     0     1     4     0     0]
 [    0     0 30484     0     2     0     0     0]
 [

In [14]:
import joblib
joblib.dump(clf2, "ids_model.pkl")
from IPython.display import FileLink
FileLink('ids_model.pkl')

/kaggle/working/ids_model.pkl